### ISSUE TITLE
Incorrect References

### ISSUE THREAD

**Issue by ben-norton** [dipeshsukhia/laravel-country-state-city-data#21]
States should always be referred to as First Order Geopolitical Divisions. Only 17 countries of 249 have first-order divisions called 'State' or 'States'. See https://gadm.org/. I highly recommend providing a source and metadata regarding the format. Currently, all of the country names are lowercase, which is not particularly useful.
I know this may seem a bit overzealous, but I assure you, this information is important.

**Comment by dipeshsukhia** [comment]
you can create setter for prefered case
